# -*- coding: utf-8 -*-
"""Web_scraping_Youtube.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11VfRKrZ8cMxQqGwY7dTTwCf21d8mYIuH
"""

from googleapiclient.discovery import build
import pandas as pd
from itertools import zip_longest

youTubeApiKey = "AIzaSyC3Mk9jSg2TA2x5JEDCH2oVAhIg-LdcGT4"

youtube = build('youtube', 'v3', developerKey=youTubeApiKey)

# Extraindo dados do yt Kinea
playlistID = 'PLpbom12S-UaLdu1QB6tTOyL5sf6O64As5'  # Fundos de Investimentos
playlistname = 'Fundos de Investimentos - Kinea'
nextPage_token = None

playlist_videos = []
res = youtube.playlistItems().list(part='snippet', playlistId=playlistID, maxResults=26).execute()
# O res possui uma série de infos sobre a playlist mas não está em um formato
playlist_videos = res['items']
videos_ids = list(map(lambda x: x['snippet']['resourceId']['videoId'], playlist_videos))
stats = []

for video_id in videos_ids:
    res= youtube.videos().list(part='statistics',id=video_id).execute()
    stats += res['items']

videos_title = list(map(lambda x: x['snippet']['title'], playlist_videos))
publi = list(map(lambda x: x['snippet']['publishedAt'], playlist_videos))
Descrc = list(map(lambda x: x['snippet']['description'], playlist_videos))
Thumb = list(map(lambda x: x['snippet']['thumbnails'], playlist_videos))
likes = list(map(lambda x: x['statistics']['likeCount'], stats))
views = list(map(lambda x: x['statistics']['viewCount'], stats))
favorite = list(map(lambda x: x['statistics']['favoriteCount'], stats))
Comm = list(map(lambda x: x['statistics'].get('commentCount', 0), stats))

# Criando a lista de tuplas com todas as informações correspondentes a cada vídeo
video_info = list(zip_longest(videos_title, publi, Descrc, Thumb, likes, views, favorite, Comm))

Data = pd.DataFrame(video_info, columns=['titulo', 'Publicado em', 'Descrição', 'Image Thumb', 'Likes', 'Views', 'Favoritados', 'Comentários'])

print(Data)